# Generated by Django 2.2.4 on 2019-09-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('type_of_novel', models.CharField(choices=[('ln', 'light_novel'), ('nv', 'novel'), ('rp', 'research_paper')], default='nv', max_length=2)),
                ('publish_date', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
